### ISSUE TITLE
Still under preview? 

### ISSUE THREAD

**Issue by dennisroche** [NuGet/json-ld.net#15]
I believe the README is out of date for this project. 

- the published package version `1.0.4` https://www.nuget.org/packages/json-ld.net/
- assume that this package is currently being used for NuGet v3?

**Comment by emgarten** [comment]
Thanks @dennisroche I've updated the README and added a link to 1.0.5 on nuget.org

json-ld.net is used by NuGet gallery, it looks like the preview disclaimer just hadn't been fixed up yet :smile:
