### ISSUE TITLE
Normalization Algorithm Used

### ISSUE THREAD

**Issue by RobTrainer** [NuGet/json-ld.net#17]
Is the processor using URGNA2012 (http://json-ld.github.io/normalization/spec/#urgna2012) or URDNA2015 (http://json-ld.github.io/normalization/spec/) for normalization?

**Comment by emgarten** [comment]
@RobTrainer didi you find the answer?

**Comment by RobTrainer** [comment]
Actually, I thought that I had but in the end it was not answered.

**Comment by RobTrainer** [comment]
So the answer appears to that the processor to only supports 2012 normalization.
