### ISSUE TITLE
Improve verification of DOM string IRI

### ISSUE THREAD

**Issue by object** [NuGet/json-ld.net#2]
This one is marked in the source code as "TODO" item, however I would like to emphasize its importance. Right now if I serialize and object into a JSON string and send it to JsonLdProcessor.Expand, it will mistakenly interpret it as a URI and of course fail. This is due to very weak check if in the code:

(input.Type == JTokenType.String && ((string)input).Contains(":"))

If it's a URI string that is expected would it be sufficient to match a regex here?

**Comment by emgarten** [comment]
@object thanks for the PR for this! It has been merged into 1.0.5

NuGet/json-ld.net@5bdd4e8877ec95b7edf5cc2fc4629421752ddbea
